#pragma kernel CSMain

float DeltaTime;

float WanderRadius;
float WanderDistance;
float WanderJitter;


struct BoidData
{
    float2 pos;
    float2 vel;
};

RWStructuredBuffer<BoidData> BoidDataBuffer;

void Move(uint3 id)
{
    BoidDataBuffer[id.x].pos += BoidDataBuffer[id.x].vel * DeltaTime;
}

[numthreads(8,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    Move(id);


    // TODO: insert actual code here!
}
